module "Windows" {
  is_windows_image = "1"
  source         = "github.com/jonhowe/TF-vSphereVM/"
  vsphere_server = "vcenter.home.lab"
  vsphere_user = "administrator@vsphere.local"
  vsphere_password = "VMware1!"
  adminpassword = "terraform"
  datacenter = "VirtJunkie-DC"
  datastore = "vsanDatastore"
  cluster = "VirtJunkie"
  portgroup = "100-LabNetwork"
  domain_name = "home.lab"
  default_gw = "172.16.1.1"
  template_name = "WS19"
  vm_name = "WS19-1"
  vm_ip = "172.16.1.150"
  vm_cidr = 24
  vcpu_count = 1
  memory = 1024
}
